package com.js.download.manager.mapper;

import com.js.download.manager.model.DownloadProcess;
import com.js.download.manager.util.QueryUtils;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface DownloadProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOWNLOAD_PROCESS_CLIENT
     *
     * @mbg.generated Tue Apr 02 12:17:28 CST 2019
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOWNLOAD_PROCESS_CLIENT
     *
     * @mbg.generated Tue Apr 02 12:17:28 CST 2019
     */
    int insert(DownloadProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOWNLOAD_PROCESS_CLIENT
     *
     * @mbg.generated Tue Apr 02 12:17:28 CST 2019
     */
    int insertSelective(DownloadProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOWNLOAD_PROCESS_CLIENT
     *
     * @mbg.generated Tue Apr 02 12:17:28 CST 2019
     */
    DownloadProcess selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOWNLOAD_PROCESS_CLIENT
     *
     * @mbg.generated Tue Apr 02 12:17:28 CST 2019
     */
    int updateByPrimaryKeySelective(DownloadProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOWNLOAD_PROCESS_CLIENT
     *
     * @mbg.generated Tue Apr 02 12:17:28 CST 2019
     */
    int updateByPrimaryKey(DownloadProcess record);

    public List<DownloadProcess> selectByUserIdFileId(@Param("userId")String userId,@Param("fileId")String fileId);

    public List<Map<String,Object>> selectByUser(@Param("queryUtils") QueryUtils queryUtils,@Param("startNum")Integer startNum,@Param("endNum")Integer endNum);

    public String getDocNoById(@Param("id")String id);

    public String getMediaNameById(@Param("id")String id);

    public  Integer getTotalNum(@Param("queryUtils") QueryUtils queryUtils);

}